### ISSUE TITLE
Getting-Started wiki has malformed url under Install MongoDB

### ISSUE THREAD

**Issue by djpdude** [evergreen-ci/evergreen#1]
https://github.com/evergreen-ci/evergreen/wiki/Getting-Started - the URL linked to "here" under "Install MongoDB" is malformed:
http://http//docs.mongodb.org/manual/installation/

**Comment by mpobrien** [comment]
Fixed. Thank you!

**Comment by djpdude** [comment]
YW :)  It was easy to workaround taking a closer look at the url - particularly as I've used MongoDB in other contexts.  Evergreen build complete!  Trying to sort out "Configure and Run", wondering: "where does this <config>.yml live?" and "what do I run?"...

**Comment by 3rf** [comment]
Hi and thanks for trying this out! For now, the .yml config can live anywhere. We recommend you pass it to the server and runner processes with the `-conf /path/to/config.yml`. As for those server and runner processes, Evergreen has 3 executables you need to use in order to run it:
`evergreen_api_server` which handles agent communication,
`evergreen_ui_server` which is our web front-end,
and `evergreen_runner`, which handles repository tracking and starting up tasks.

These can all be executed with that -conf flag. Right now the documentation is lacking regarding config files and initial startup, so I hope to get that section fleshed out with more detail sometime today. Thanks again for checking out Evergreen and for your patience :)

**Comment by djpdude** [comment]
Thanks much!  I completely understand that y'all have Just Started the
process of open-sourcing all of this, so thanks for THAT, and I hope the
benefits will be mutual.

:^)
djp
