### ISSUE TITLE
Update readme, wiki, and building to reflect changes in Go 1.5

### ISSUE THREAD

**Issue by farazfazli** [evergreen-ci/evergreen#35]
Go 1.5 no longer requires Go to be build from source for cross compiling. A new file, build_15_agent.sh can be created for users with Go 1.5 and up which cross compiles using the GOOS and GOARCH environmental variables.

**Comment by mpobrien** [comment]
Thanks @farazfazli. We do have a script which does this here: https://github.com/evergreen-ci/evergreen/blob/master/build_agent_gc.sh
We haven't migrated everything to use 1.5 features extensively yet because of a few issues that became blockers for us, most notably https://github.com/golang/go/issues/13164 since it affects tasks spawned by task runner agents. We will most likely make a batch of updates around this theme once 1.6 is released, however.

**Comment by farazfazli** [comment]
@mpobrien Got it, thanks for the info.

**Comment by mpobrien** [comment]
Now that 1.6 is out, cross compiling agents is a viable option, so I've updated the README accordingly. Thanks!
